
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 *
 */
public class DoctorOTPVerification extends javax.swing.JFrame {

    // Email of the user who requested password reset
    private String userEmail;

    // OTP that was sent to the user's email
    private String generatedOTP;

    // Time when OTP was generated
    private long otpGeneratedTime;

    // Number of wrong OTP attempts
    private int attempts = 0;

    // OTP valid for 5 minutes
    private static final long OTP_VALIDITY
            = 5 * 60 * 1000;

    // Maximum 5 incorrect attempts
    private static final int MAX_ATTEMPTS = 5;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorOTPVerification.class.getName());

    public DoctorOTPVerification(String email, String otp) {
        initComponents();
        // Store email and OTP
        this.userEmail = email;
        this.generatedOTP = otp;

        // Start OTP timer
        this.otpGeneratedTime = System.currentTimeMillis();

        // Reset attempts
        this.attempts = 0;

        // Show email on the OTP screen
        jLabel7.setText("OTP sent to: " + email);

        // Start with empty OTP field
        jTextField1.setText("");

        // Closing this window should NOT close the whole application
        setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );

        setSize(1200, 700);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OTP Verification");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setPreferredSize(new java.awt.Dimension(1150, 700));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 245, 255));
        jPanel1.setForeground(new java.awt.Color(93, 106, 127));
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 58, 113));
        jLabel1.setText("Doctor Consultation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 58, 113));
        jLabel2.setText("System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doc1-2.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 530, 440));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/01_logo_heart_pulse-2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(247, 250, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("  OTP sent to:");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(15, 45, 103));
        jLabel13.setText("VERIFY THE OTP");

        jLabel14.setForeground(new java.awt.Color(18, 58, 122));
        jLabel14.setText("──────── ♥️ ────────");

        jButton1.setBackground(new java.awt.Color(45, 127, 249));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VERIFY");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/08_feature_secure_account-2.png"))); // NOI18N

        jButton3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(45, 127, 249));
        jButton3.setText("Resend OTP");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jTextField1.setText("Enter OTP");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 185, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 45, 620, 610));

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 997));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String enteredOTP
                = jTextField1.getText().trim();

        // --------------------------------
        // 1. Check if OTP is empty
        // --------------------------------
        if (enteredOTP.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter the OTP."
            );

            return;
        }

        // --------------------------------
        // 2. OTP must contain 6 digits
        // --------------------------------
        if (!enteredOTP.matches("\\d{6}")) {

            JOptionPane.showMessageDialog(
                    this,
                    "OTP must contain exactly 6 digits."
            );

            return;
        }

        // --------------------------------
        // 3. Check maximum attempts
        // --------------------------------
        if (attempts >= MAX_ATTEMPTS) {

            JOptionPane.showMessageDialog(
                    this,
                    "Too many incorrect attempts.\n"
                    + "Please click Resend OTP."
            );

            return;
        }

        // --------------------------------
        // 4. Check OTP expiry
        // --------------------------------
        long currentTime
                = System.currentTimeMillis();

        long elapsedTime
                = currentTime - otpGeneratedTime;

        if (elapsedTime > OTP_VALIDITY) {

            JOptionPane.showMessageDialog(
                    this,
                    "OTP has expired.\n"
                    + "Please click Resend OTP."
            );

            return;
        }

        // --------------------------------
        // 5. Compare OTP
        // --------------------------------
        if (enteredOTP.equals(generatedOTP)) {

            JOptionPane.showMessageDialog(
                    this,
                    "OTP verified successfully."
            );

            // Open Reset Password page
            DoctorResetPassword resetPage
                    = new DoctorResetPassword(userEmail);

            resetPage.setLocationRelativeTo(null);
            resetPage.setVisible(true);

            // Close OTP window
            this.dispose();

        } else {

            attempts++;

            int remainingAttempts
                    = MAX_ATTEMPTS - attempts;

            if (remainingAttempts > 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Incorrect OTP.\n"
                        + "Attempts remaining: "
                        + remainingAttempts
                );

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Incorrect OTP.\n"
                        + "Maximum attempts reached.\n"
                        + "Please click Resend OTP."
                );
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // Generate a new OTP
        String newOTP
                = OTPUtil.generateOTP();

        // Send new OTP to the same email
        boolean sent
                = EmailSender.sendOTP(
                        userEmail,
                        newOTP
                );

        if (sent) {

            // Replace old OTP
            generatedOTP = newOTP;

            // Restart 5-minute timer
            otpGeneratedTime
                    = System.currentTimeMillis();

            // Reset wrong attempts
            attempts = 0;

            // Clear OTP field
            jTextField1.setText("");

            JOptionPane.showMessageDialog(
                    this,
                    "A new OTP has been sent to:\n"
                    + userEmail
            );

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Unable to send OTP.\n"
                    + "Please try again."
            );
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
